pcie: Fix the compilation errors
Fix compilation errors caused by function type mismatch.

drivers/pci/controller/cadence/pcie-cadence-sophgo.c:403:12: error: conflicting types for 'cdns_pcie_host_init'; have 'int(struct device *, struct cdns_mango_pcie_rc *)'
  403 | static int cdns_pcie_host_init(struct device *dev, struct cdns_mango_pcie_rc *rc)
      |            ^~~~~~~~~~~~~~~~~~~
In file included from drivers/pci/controller/cadence/pcie-cadence-sophgo.c:16:
drivers/pci/controller/cadence/pcie-cadence.h:519:5: note: previous declaration of 'cdns_pcie_host_init' with type 'int(struct cdns_pcie_rc *)'
  519 | int cdns_pcie_host_init(struct cdns_pcie_rc *rc);
      |     ^~~~~~~~~~~~~~~~~~~

Signed-off-by: haijiao.liu <haijiao.liu@sophgo.com>